export const REQUEST_SIGNIN = "@USER/REQUEST_SIGNIN";
export const AUTH_SUCCESS = "@USER/AUTH_SUCCESS";
export const AUTH_FAILURE = "@USER/AUTH_FAILURE";
export const REQUEST_SIGNOUT = "@USER/REQUEST_SIGNOUT";
export const SIGNOUT_SUCCESS = "@USER/SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "@USER/SIGNOUT_FAILURE";
