export const RESOLVE_TRACK = "@TRACKS/RESOLVE";
export const FETCH_TRACKS = "@TRACKS/FETCH";
export const UPDATE_TRACK = "@TRACKS/UPDATE_TRACK";
export const UPDATE_TRACK_DATA = "@TRACKS/UPDATE_TRACK_DATA";
